BEGIN;
CREATE TABLE import.batches (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL REFERENCES core.products(id),
 statement_period DATE NOT NULL CHECK(statement_period = date_trunc('month', statement_period)::date),
 status VARCHAR(30) NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','processing','completed','partially_completed','failed','cancelled')),
 source_type VARCHAR(30), total_records BIGINT NOT NULL DEFAULT 0 CHECK(total_records >= 0),
 valid_records BIGINT NOT NULL DEFAULT 0 CHECK(valid_records >= 0), invalid_records BIGINT NOT NULL DEFAULT 0 CHECK(invalid_records >= 0),
 processed_records BIGINT NOT NULL DEFAULT 0 CHECK(processed_records >= 0), created_by BIGINT REFERENCES core.users(id) ON DELETE SET NULL,
 started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, failed_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE import.files (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, batch_id BIGINT NOT NULL REFERENCES import.batches(id) ON DELETE CASCADE,
 original_name VARCHAR(255) NOT NULL, storage_key TEXT NOT NULL, mime_type VARCHAR(100), size_bytes BIGINT CHECK(size_bytes IS NULL OR size_bytes >= 0),
 checksum VARCHAR(128), status VARCHAR(30) NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','processing','completed','failed','quarantined')),
 total_rows BIGINT NOT NULL DEFAULT 0, processed_rows BIGINT NOT NULL DEFAULT 0, valid_rows BIGINT NOT NULL DEFAULT 0, invalid_rows BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE import.records (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, batch_id BIGINT NOT NULL REFERENCES import.batches(id) ON DELETE CASCADE,
 file_id BIGINT REFERENCES import.files(id) ON DELETE SET NULL, product_id BIGINT NOT NULL REFERENCES core.products(id),
 customer_id BIGINT REFERENCES core.customers(id) ON DELETE SET NULL, customer_account_id BIGINT REFERENCES core.customer_accounts(id) ON DELETE SET NULL,
 statement_period DATE NOT NULL, customer_number VARCHAR(100), account_number VARCHAR(100) NOT NULL, customer_name VARCHAR(255),
 address_line_1 VARCHAR(255), address_line_2 VARCHAR(255), address_line_3 VARCHAR(255), city VARCHAR(100), province VARCHAR(100), postal_code VARCHAR(20),
 barcode VARCHAR(100), source_row_number BIGINT, raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
 status VARCHAR(30) NOT NULL DEFAULT 'valid' CHECK(status IN ('pending','valid','invalid','processed','failed')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE import.record_errors (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, batch_id BIGINT NOT NULL REFERENCES import.batches(id) ON DELETE CASCADE,
 file_id BIGINT REFERENCES import.files(id) ON DELETE CASCADE, record_id BIGINT REFERENCES import.records(id) ON DELETE CASCADE,
 row_number BIGINT, error_code VARCHAR(100) NOT NULL, field_name VARCHAR(100), error_message TEXT NOT NULL,
 raw_value TEXT, raw_data JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE import.events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, batch_id BIGINT NOT NULL REFERENCES import.batches(id) ON DELETE CASCADE,
 file_id BIGINT REFERENCES import.files(id) ON DELETE SET NULL, event_type VARCHAR(100) NOT NULL,
 metadata JSONB NOT NULL DEFAULT '{}'::jsonb, occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
