BEGIN;
CREATE TABLE pdf.documents (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, record_id BIGINT NOT NULL REFERENCES import.records(id),
 status VARCHAR(30) NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','processing','generated','failed','archived')),
 file_name VARCHAR(255), storage_key TEXT, mime_type VARCHAR(100) DEFAULT 'application/pdf', size_bytes BIGINT CHECK(size_bytes IS NULL OR size_bytes >= 0),
 page_count INTEGER CHECK(page_count IS NULL OR page_count >= 0), checksum VARCHAR(128), is_encrypted BOOLEAN NOT NULL DEFAULT FALSE,
 password_ciphertext TEXT, generated_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(record_id)
);
CREATE TABLE pdf.jobs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id BIGINT NOT NULL REFERENCES pdf.documents(id) ON DELETE CASCADE,
 job_type VARCHAR(30) NOT NULL CHECK(job_type IN ('generate','merge','encrypt','stamp','validate')),
 status VARCHAR(30) NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','processing','completed','failed','cancelled')),
 attempt_count INTEGER NOT NULL DEFAULT 0 CHECK(attempt_count >= 0), started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, failed_at TIMESTAMPTZ,
 error_code VARCHAR(100), error_message TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE pdf.events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id BIGINT NOT NULL REFERENCES pdf.documents(id) ON DELETE CASCADE,
 job_id BIGINT REFERENCES pdf.jobs(id) ON DELETE SET NULL, event_type VARCHAR(100) NOT NULL, metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
 occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
