BEGIN;
CREATE TABLE messaging.mail_servers (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL, host VARCHAR(255) NOT NULL,
 port INTEGER NOT NULL CHECK(port BETWEEN 1 AND 65535), username VARCHAR(255), secret_reference TEXT,
 encryption VARCHAR(20) CHECK(encryption IS NULL OR encryption IN ('none','tls','starttls')),
 from_email VARCHAR(255) NOT NULL, from_name VARCHAR(255), reply_to_email VARCHAR(255), bounce_email VARCHAR(255),
 daily_limit INTEGER CHECK(daily_limit IS NULL OR daily_limit >= 0), hourly_limit INTEGER CHECK(hourly_limit IS NULL OR hourly_limit >= 0),
 is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE messaging.templates (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id BIGINT REFERENCES core.products(id),
 mail_server_id BIGINT REFERENCES messaging.mail_servers(id), name VARCHAR(150) NOT NULL, subject TEXT NOT NULL,
 html_body TEXT, text_body TEXT, is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE messaging.deliveries (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, record_id BIGINT REFERENCES import.records(id) ON DELETE SET NULL,
 document_id BIGINT REFERENCES pdf.documents(id) ON DELETE SET NULL, template_id BIGINT REFERENCES messaging.templates(id) ON DELETE SET NULL,
 mail_server_id BIGINT REFERENCES messaging.mail_servers(id) ON DELETE SET NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','queued','processing','sent','failed','bounced','cancelled')),
 priority SMALLINT NOT NULL DEFAULT 100 CHECK(priority >= 0), subject TEXT, queued_at TIMESTAMPTZ, processing_at TIMESTAMPTZ,
 sent_at TIMESTAMPTZ, failed_at TIMESTAMPTZ, created_by BIGINT REFERENCES core.users(id) ON DELETE SET NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE messaging.recipients (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, delivery_id BIGINT NOT NULL REFERENCES messaging.deliveries(id) ON DELETE CASCADE,
 type VARCHAR(10) NOT NULL CHECK(type IN ('to','cc','bcc')), email VARCHAR(255) NOT NULL, name VARCHAR(255),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(delivery_id, type, email)
);
CREATE TABLE messaging.attachments (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, delivery_id BIGINT NOT NULL REFERENCES messaging.deliveries(id) ON DELETE CASCADE,
 document_id BIGINT REFERENCES pdf.documents(id) ON DELETE SET NULL, core_attachment_id BIGINT REFERENCES core.attachments(id) ON DELETE SET NULL,
 file_name VARCHAR(255) NOT NULL, storage_key TEXT NOT NULL, mime_type VARCHAR(100), size_bytes BIGINT CHECK(size_bytes IS NULL OR size_bytes >= 0),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CHECK(document_id IS NOT NULL OR core_attachment_id IS NOT NULL)
);
CREATE TABLE messaging.delivery_attempts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, delivery_id BIGINT NOT NULL REFERENCES messaging.deliveries(id) ON DELETE CASCADE,
 mail_server_id BIGINT REFERENCES messaging.mail_servers(id) ON DELETE SET NULL, attempt_number INTEGER NOT NULL CHECK(attempt_number > 0),
 status VARCHAR(30) NOT NULL CHECK(status IN ('processing','sent','failed','timeout')),
 provider_message_id VARCHAR(255), started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, failed_at TIMESTAMPTZ,
 error_code VARCHAR(100), error_message TEXT, response_data JSONB NOT NULL DEFAULT '{}'::jsonb,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(delivery_id, attempt_number)
);
CREATE TABLE messaging.delivery_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, delivery_id BIGINT NOT NULL REFERENCES messaging.deliveries(id) ON DELETE CASCADE,
 attempt_id BIGINT REFERENCES messaging.delivery_attempts(id) ON DELETE SET NULL,
 event_type VARCHAR(30) NOT NULL CHECK(event_type IN ('queued','sending','sent','delivered','opened','clicked','bounced','complained','failed')),
 provider_event_id VARCHAR(255), metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
 occurred_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE messaging.suppressions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email VARCHAR(255) NOT NULL,
 reason VARCHAR(30) NOT NULL CHECK(reason IN ('hard_bounce','complaint','unsubscribe','manual','invalid_address')),
 source VARCHAR(100), is_permanent BOOLEAN NOT NULL DEFAULT TRUE, expires_at TIMESTAMPTZ,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(email, reason)
);
COMMIT;
