BEGIN;
CREATE INDEX idx_customer_accounts_customer ON core.customer_accounts(customer_id);
CREATE INDEX idx_customer_contacts_customer ON core.customer_contacts(customer_id);
CREATE UNIQUE INDEX uq_customer_primary_contact ON core.customer_contacts(customer_id, type) WHERE is_primary AND is_active;
CREATE INDEX idx_audit_logs_entity ON core.audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_logs_created_at ON core.audit_logs(created_at);
CREATE INDEX idx_batches_product_period ON import.batches(product_id, statement_period);
CREATE INDEX idx_batches_status_created ON import.batches(status, created_at);
CREATE INDEX idx_files_batch ON import.files(batch_id);
CREATE INDEX idx_records_batch ON import.records(batch_id);
CREATE INDEX idx_records_file ON import.records(file_id);
CREATE INDEX idx_records_product_period ON import.records(product_id, statement_period);
CREATE INDEX idx_records_account_period ON import.records(account_number, statement_period);
CREATE INDEX idx_records_customer_number_period ON import.records(customer_number, statement_period) WHERE customer_number IS NOT NULL;
CREATE INDEX idx_record_errors_batch ON import.record_errors(batch_id);
CREATE INDEX idx_documents_status ON pdf.documents(status);
CREATE INDEX idx_jobs_pending ON pdf.jobs(created_at) WHERE status = 'pending';
CREATE INDEX idx_deliveries_record ON messaging.deliveries(record_id);
CREATE INDEX idx_deliveries_document ON messaging.deliveries(document_id);
CREATE INDEX idx_deliveries_queue ON messaging.deliveries(priority, queued_at, id) WHERE status = 'queued';
CREATE INDEX idx_recipients_email ON messaging.recipients(email);
CREATE INDEX idx_attempts_delivery ON messaging.delivery_attempts(delivery_id, attempt_number);
CREATE INDEX idx_events_delivery_occurred ON messaging.delivery_events(delivery_id, occurred_at);
CREATE INDEX idx_suppressions_permanent_email ON messaging.suppressions(email) WHERE is_permanent;
CREATE INDEX idx_suppressions_expires_at ON messaging.suppressions(expires_at) WHERE expires_at IS NOT NULL;
COMMIT;
