<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('import.batches',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained('core.products');$t->date('statement_period');$t->string('status',30)->default('pending');$t->string('source_type',30)->nullable();$t->unsignedBigInteger('total_records')->default(0);$t->unsignedBigInteger('valid_records')->default(0);$t->unsignedBigInteger('invalid_records')->default(0);$t->unsignedBigInteger('processed_records')->default(0);$t->foreignId('created_by')->nullable()->constrained('core.users')->nullOnDelete();$t->timestampTz('started_at')->nullable();$t->timestampTz('completed_at')->nullable();$t->timestampTz('failed_at')->nullable();$t->timestampsTz();$t->index(['product_id','statement_period']);$t->index(['status','created_at']);});
  DB::statement("ALTER TABLE import.batches ADD CONSTRAINT batches_status_check CHECK (status IN ('pending','processing','completed','partially_completed','failed','cancelled'))");
  Schema::create('import.files',function(Blueprint $t){$t->id();$t->foreignId('batch_id')->constrained('import.batches')->cascadeOnDelete();$t->string('original_name');$t->text('storage_key');$t->string('mime_type',100)->nullable();$t->unsignedBigInteger('size_bytes')->nullable();$t->string('checksum',128)->nullable();$t->string('status',30)->default('pending');$t->unsignedBigInteger('total_rows')->default(0);$t->unsignedBigInteger('processed_rows')->default(0);$t->unsignedBigInteger('valid_rows')->default(0);$t->unsignedBigInteger('invalid_rows')->default(0);$t->timestampsTz();$t->index('batch_id');});
  Schema::create('import.records',function(Blueprint $t){$t->id();$t->foreignId('batch_id')->constrained('import.batches')->cascadeOnDelete();$t->foreignId('file_id')->nullable()->constrained('import.files')->nullOnDelete();$t->foreignId('product_id')->constrained('core.products');$t->foreignId('customer_id')->nullable()->constrained('core.customers')->nullOnDelete();$t->foreignId('customer_account_id')->nullable()->constrained('core.customer_accounts')->nullOnDelete();$t->date('statement_period');$t->string('customer_number',100)->nullable();$t->string('account_number',100);$t->string('customer_name')->nullable();$t->string('address_line_1')->nullable();$t->string('address_line_2')->nullable();$t->string('address_line_3')->nullable();$t->string('city',100)->nullable();$t->string('province',100)->nullable();$t->string('postal_code',20)->nullable();$t->string('barcode',100)->nullable();$t->unsignedBigInteger('source_row_number')->nullable();$t->jsonb('raw_data')->nullable();$t->string('status',30)->default('valid');$t->timestampsTz();$t->index('batch_id');$t->index('file_id');$t->index(['product_id','statement_period']);$t->index(['account_number','statement_period']);});
  Schema::create('import.record_errors',function(Blueprint $t){$t->id();$t->foreignId('batch_id')->constrained('import.batches')->cascadeOnDelete();$t->foreignId('file_id')->nullable()->constrained('import.files')->cascadeOnDelete();$t->foreignId('record_id')->nullable()->constrained('import.records')->cascadeOnDelete();$t->unsignedBigInteger('row_number')->nullable();$t->string('error_code',100);$t->string('field_name',100)->nullable();$t->text('error_message');$t->text('raw_value')->nullable();$t->jsonb('raw_data')->nullable();$t->timestampTz('created_at')->useCurrent();$t->index('batch_id');});
  Schema::create('import.events',function(Blueprint $t){$t->id();$t->foreignId('batch_id')->constrained('import.batches')->cascadeOnDelete();$t->foreignId('file_id')->nullable()->constrained('import.files')->nullOnDelete();$t->string('event_type',100);$t->jsonb('metadata')->nullable();$t->timestampTz('occurred_at')->useCurrent();});
 }
 public function down():void {foreach(['events','record_errors','records','files','batches'] as $table){Schema::dropIfExists("import.$table");}}
};