<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void {
  Schema::create('messaging.mail_servers',function(Blueprint $t){$t->id();$t->string('name',100);$t->string('host');$t->unsignedSmallInteger('port');$t->string('username')->nullable();$t->text('secret_reference')->nullable();$t->string('encryption',20)->nullable();$t->string('from_email');$t->string('from_name')->nullable();$t->string('reply_to_email')->nullable();$t->string('bounce_email')->nullable();$t->string('inbox_email')->nullable();$t->unsignedInteger('daily_limit')->nullable();$t->unsignedInteger('hourly_limit')->nullable();$t->boolean('is_active')->default(true);$t->timestampsTz();});
  Schema::create('messaging.templates',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained('core.products');$t->foreignId('mail_server_id')->constrained('messaging.mail_servers');$t->string('name',150);$t->text('subject');$t->text('html_body')->nullable();$t->text('text_body')->nullable();$t->boolean('is_active')->default(true);$t->timestampsTz();$t->unique(['product_id','name']);});
  Schema::create('messaging.deliveries',function(Blueprint $t){$t->id();$t->foreignId('statement_id')->constrained('import.statements');$t->foreignId('document_id')->nullable()->constrained('pdf.documents')->nullOnDelete();$t->foreignId('template_id')->constrained('messaging.templates');$t->foreignId('mail_server_id')->constrained('messaging.mail_servers');$t->string('status',30)->default('draft');$t->unsignedSmallInteger('priority')->default(100);$t->text('subject');$t->timestampTz('scheduled_at')->nullable();$t->timestampTz('queued_at')->nullable();$t->timestampTz('processing_at')->nullable();$t->timestampTz('sent_at')->nullable();$t->timestampTz('failed_at')->nullable();$t->foreignId('created_by')->nullable()->constrained('core.users')->nullOnDelete();$t->timestampsTz();$t->index('statement_id');$t->index('document_id');});
  Schema::create('messaging.recipients',function(Blueprint $t){$t->id();$t->foreignId('delivery_id')->constrained('messaging.deliveries')->cascadeOnDelete();$t->foreignId('customer_contact_id')->nullable()->constrained('import.customer_contacts')->nullOnDelete();$t->string('type',10);$t->string('email');$t->string('name')->nullable();$t->timestampTz('created_at')->useCurrent();$t->unique(['delivery_id','type','email']);$t->index('email');});
  Schema::create('messaging.attachments',function(Blueprint $t){$t->id();$t->foreignId('delivery_id')->constrained('messaging.deliveries')->cascadeOnDelete();$t->foreignId('document_id')->nullable()->constrained('pdf.documents')->nullOnDelete();$t->foreignId('core_attachment_id')->nullable()->constrained('core.attachments')->nullOnDelete();$t->string('file_name');$t->text('storage_key');$t->string('mime_type',100)->nullable();$t->unsignedBigInteger('size_bytes')->nullable();$t->timestampTz('created_at')->useCurrent();});
  Schema::create('messaging.delivery_attempts',function(Blueprint $t){$t->id();$t->foreignId('delivery_id')->constrained('messaging.deliveries')->cascadeOnDelete();$t->foreignId('mail_server_id')->constrained('messaging.mail_servers');$t->unsignedInteger('attempt_number');$t->string('status',30);$t->string('provider_message_id')->nullable();$t->timestampTz('started_at')->nullable();$t->timestampTz('completed_at')->nullable();$t->timestampTz('failed_at')->nullable();$t->string('error_code',100)->nullable();$t->text('error_message')->nullable();$t->jsonb('response_data')->nullable();$t->timestampTz('created_at')->useCurrent();$t->unique(['delivery_id','attempt_number']);});
  Schema::create('messaging.delivery_events',function(Blueprint $t){$t->id();$t->foreignId('delivery_id')->constrained('messaging.deliveries')->cascadeOnDelete();$t->foreignId('attempt_id')->nullable()->constrained('messaging.delivery_attempts')->nullOnDelete();$t->string('event_type',30);$t->string('provider_event_id')->nullable();$t->jsonb('metadata')->nullable();$t->timestampTz('occurred_at');$t->timestampTz('created_at')->useCurrent();$t->index(['delivery_id','occurred_at']);});
  Schema::create('messaging.suppressions',function(Blueprint $t){$t->id();$t->string('email');$t->string('reason',30);$t->string('source',100)->nullable();$t->boolean('is_permanent')->default(true);$t->timestampTz('expires_at')->nullable();$t->timestampsTz();$t->unique(['email','reason']);});
  DB::statement("ALTER TABLE messaging.mail_servers ADD CONSTRAINT mail_servers_encryption_check CHECK (encryption IS NULL OR encryption IN ('none','tls','starttls'))");
  DB::statement("ALTER TABLE messaging.deliveries ADD CONSTRAINT deliveries_status_check CHECK (status IN ('draft','scheduled','queued','processing','sent','failed','bounced','cancelled'))");
  DB::statement("ALTER TABLE messaging.recipients ADD CONSTRAINT recipients_type_check CHECK (type IN ('to','cc','bcc'))");
  DB::statement("ALTER TABLE messaging.attachments ADD CONSTRAINT attachments_source_check CHECK (document_id IS NOT NULL OR core_attachment_id IS NOT NULL)");
  DB::statement("CREATE INDEX idx_deliveries_queue ON messaging.deliveries (priority, queued_at, id) WHERE status = 'queued'");
  DB::statement("CREATE INDEX idx_suppressions_permanent_email ON messaging.suppressions (email) WHERE is_permanent");
 }
 public function down():void {foreach(['delivery_events','delivery_attempts','attachments','recipients','deliveries','templates','suppressions','mail_servers'] as $table){Schema::dropIfExists("messaging.$table");}}
};